/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'on-accent': 'rgb(var(--color-on-accent) / <alpha-value>)',
        'switch-thumb': 'rgb(var(--color-switch-thumb) / <alpha-value>)',
        brand: {
          50: '#fff7ed',
          200: 'rgb(var(--color-brand-200) / <alpha-value>)',
          300: 'rgb(var(--color-brand-300) / <alpha-value>)',
          400: 'rgb(var(--color-brand-400) / <alpha-value>)',
          500: 'rgb(var(--color-brand-500) / <alpha-value>)',
          600: 'rgb(var(--color-brand-600) / <alpha-value>)',
        },
        ink: {
          900: '#0f172a',
          700: '#334155',
          500: '#64748b',
        },
        amber: {
          100: 'rgb(var(--color-amber-100) / <alpha-value>)',
          200: 'rgb(var(--color-amber-200) / <alpha-value>)',
          300: 'rgb(var(--color-amber-300) / <alpha-value>)',
          500: 'rgb(var(--color-amber-500) / <alpha-value>)',
          600: 'rgb(var(--color-amber-600) / <alpha-value>)',
          700: 'rgb(var(--color-amber-700) / <alpha-value>)',
          800: 'rgb(var(--color-amber-800) / <alpha-value>)',
          950: 'rgb(var(--color-amber-950) / <alpha-value>)',
        },
        cyan: {
          200: 'rgb(var(--color-cyan-200) / <alpha-value>)',
          300: 'rgb(var(--color-cyan-300) / <alpha-value>)',
          400: 'rgb(var(--color-cyan-400) / <alpha-value>)',
          500: 'rgb(var(--color-cyan-500) / <alpha-value>)',
          700: 'rgb(var(--color-cyan-700) / <alpha-value>)',
          800: 'rgb(var(--color-cyan-800) / <alpha-value>)',
          900: 'rgb(var(--color-cyan-900) / <alpha-value>)',
          950: 'rgb(var(--color-cyan-950) / <alpha-value>)',
        },
        emerald: {
          300: 'rgb(var(--color-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--color-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--color-emerald-500) / <alpha-value>)',
        },
        orange: {
          300: 'rgb(var(--color-orange-300) / <alpha-value>)',
          500: 'rgb(var(--color-orange-500) / <alpha-value>)',
        },
        red: {
          100: 'rgb(var(--color-red-100) / <alpha-value>)',
          200: 'rgb(var(--color-red-200) / <alpha-value>)',
          300: 'rgb(var(--color-red-300) / <alpha-value>)',
          900: 'rgb(var(--color-red-900) / <alpha-value>)',
          950: 'rgb(var(--color-red-950) / <alpha-value>)',
        },
        slate: {
          50: 'rgb(var(--color-slate-50) / <alpha-value>)',
          100: 'rgb(var(--color-slate-100) / <alpha-value>)',
          200: 'rgb(var(--color-slate-200) / <alpha-value>)',
          300: 'rgb(var(--color-slate-300) / <alpha-value>)',
          400: 'rgb(var(--color-slate-400) / <alpha-value>)',
          500: 'rgb(var(--color-slate-500) / <alpha-value>)',
          600: 'rgb(var(--color-slate-600) / <alpha-value>)',
          700: 'rgb(var(--color-slate-700) / <alpha-value>)',
          800: 'rgb(var(--color-slate-800) / <alpha-value>)',
          900: 'rgb(var(--color-slate-900) / <alpha-value>)',
          950: 'rgb(var(--color-slate-950) / <alpha-value>)',
        },
        sky: {
          800: 'rgb(var(--color-sky-800) / <alpha-value>)',
          950: 'rgb(var(--color-sky-950) / <alpha-value>)',
        },
        white: 'rgb(var(--color-foreground) / <alpha-value>)',
      },
    },
  },
  plugins: [],
};
